"""Tests for snapshot saving."""

import numpy as np

from ledportal_pro.ui.snapshot import SnapshotManager


class TestSnapshotManager:
    """SnapshotManager creates files in the right place with the right names."""

    def test_output_dir_created(self, tmp_path):
        out = tmp_path / "snapshots"
        manager = SnapshotManager(output_dir=out)
        assert out.exists()
        assert manager.output_dir == out

    def test_save_creates_bmp(self, tmp_path):
        manager = SnapshotManager(output_dir=tmp_path)
        frame = np.zeros((32, 64, 3), dtype=np.uint8)

        image_path, debug_path, rgb565_path, pdf_path = manager.save(frame)

        assert image_path.exists()
        assert image_path.suffix == ".bmp"
        assert image_path.name.startswith("snapshot_")
        # No debug mode → no debug files
        assert debug_path is None
        assert rgb565_path is None
        # Letter PDF generated by default
        assert pdf_path is not None
        assert pdf_path.exists()
        assert pdf_path.suffix == ".pdf"
        assert "_4x6" not in pdf_path.name

    def test_save_creates_bmp_and_bin_in_debug_mode(self, tmp_path):
        manager = SnapshotManager(output_dir=tmp_path)
        frame = np.zeros((32, 64, 3), dtype=np.uint8)
        raw = b"\x00" * (64 * 32 * 2)

        image_path, debug_path, rgb565_path, pdf_path = manager.save(
            frame, frame_bytes=raw, debug_mode=True
        )

        assert image_path.exists()
        assert debug_path is not None
        assert debug_path.exists()
        assert rgb565_path is not None
        assert rgb565_path.exists()
        assert rgb565_path.suffix == ".bin"
        assert rgb565_path.read_bytes() == raw

    def test_save_custom_prefix(self, tmp_path):
        manager = SnapshotManager(output_dir=tmp_path)
        frame = np.zeros((32, 64, 3), dtype=np.uint8)

        image_path, _, _, _ = manager.save(frame, prefix="avatar_front")

        assert image_path.name.startswith("avatar_front_")

    def test_save_no_letter_pdf_when_disabled(self, tmp_path):
        manager = SnapshotManager(output_dir=tmp_path)
        frame = np.zeros((32, 64, 3), dtype=np.uint8)

        _, _, _, pdf_path = manager.save(frame, export_pdf_flag=False)

        assert pdf_path is None
        assert not any(f.suffix == ".pdf" and "_4x6" not in f.name for f in tmp_path.iterdir())

    def test_save_export_4x6_creates_file(self, tmp_path):
        manager = SnapshotManager(output_dir=tmp_path)
        frame = np.zeros((32, 64, 3), dtype=np.uint8)

        manager.save(frame, export_4x6=True)

        files_4x6 = [f for f in tmp_path.iterdir() if "_4x6" in f.name]
        assert len(files_4x6) == 1
        assert files_4x6[0].suffix == ".pdf"

    def test_auto_print_implies_4x6_created(self, tmp_path, monkeypatch):
        """auto_print=True should create the 4×6 PDF even if export_4x6=False.

        The print dispatch is stubbed so the test never shells out to a real
        printer/`lpr` — it verifies only that auto_print implies the 4×6 file.
        """
        import ledportal_pro.ui.snapshot as snapshot_mod

        dispatched = []
        monkeypatch.setattr(snapshot_mod, "_dispatch_print", lambda path: dispatched.append(path))

        manager = SnapshotManager(output_dir=tmp_path)
        frame = np.zeros((32, 64, 3), dtype=np.uint8)
        manager.save(frame, export_4x6=False, auto_print=True)

        files_4x6 = [f for f in tmp_path.iterdir() if "_4x6" in f.name]
        assert len(files_4x6) == 1
        # auto_print should have dispatched the created 4×6 PDF to the printer
        assert dispatched == [files_4x6[0]]

    def test_dispatch_print_survives_missing_lpr(self, tmp_path, monkeypatch):
        """_dispatch_print must not crash when lpr is absent (no CUPS installed)."""
        import subprocess

        import ledportal_pro.ui.snapshot as snapshot_mod

        monkeypatch.setattr(snapshot_mod.sys, "platform", "linux")

        def _raise_missing(*_args, **_kwargs):
            raise FileNotFoundError(2, "No such file or directory", "lpr")

        monkeypatch.setattr(subprocess, "run", _raise_missing)

        # Should print a warning and return, not raise
        snapshot_mod._dispatch_print(tmp_path / "x_4x6.pdf")

    def test_save_debug_frame_overwrites(self, tmp_path):
        manager = SnapshotManager(output_dir=tmp_path)
        frame1 = np.zeros((32, 64, 3), dtype=np.uint8)
        frame2 = np.full((32, 64, 3), 128, dtype=np.uint8)

        path1 = manager.save_debug_frame(frame1)
        path2 = manager.save_debug_frame(frame2)

        # Same path — debug frame always overwrites
        assert path1 == path2
        assert path2.exists()
